driver:
  name: ec2
  aws_ssh_key_id: ac-staging
  transport.ssh_key: ~/.ssh/ac-staging.pem
  region: us-west-2
  require_chef_omnibus: true
  associate_public_ip: true
  interface: dns
  instance_type: t1.micro

provisioner:
  name: chef_zero
  role_path: /Users/jesiegel/Desktop/workspace/Rails/chef/alphachannel/roles

platforms:
  - name: amazon
    driver:
      image_id: ami-8e49efee
    transport:
      username: ubuntu

suites:
  - name: default
    run_list:
      - recipe[alphachannel::default]
      - recipe[alphachannel::nginx]
      - recipe[alphachannel::ffmpeg]
    attributes:
